name: Release new hfinger version

on:
  release:
    types: [published]

jobs:
  release_pypi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build package
      run: |
        pip3 install setuptools wheel
        python3 setup.py bdist_wheel
    - name: Publish to PyPi
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
